name: Build Linux

on:
  push:
    paths:
      - 'linux'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Download Zips
      shell: bash
      run: |
        ./install-deps.sh
        LATEST_COMMIT_ID=${git rev-parse HEAD:linux}
        wget https://github.com/vsfe/linux/archive/${LATEST_COMMIT_ID}.zip
        unzip -q ${LATEST_COMMIT_ID}.zip
        ./build-linux.sh ./linux-${LATEST_COMMIT_ID} tinyconfig